import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-b from-radial-gradient-start to-radial-gradient-end bg-no-repeat bg-cover min-h-screen'>
        {children}
      </body>
    </html>
  )
}
